# Generated by Django 3.2.16 on 2022-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_auto_20221226_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="default_transcript_type",
            field=models.CharField(
                choices=[
                    ("ORIGINAL_SOURCE", "Original Source"),
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="default transcript type",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_translation_type",
            field=models.CharField(
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="Default Translation Type",
            ),
        ),
    ]
