# Generated by Django 3.2.16 on 2023-01-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0004_auto_20230103_0526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="default_transcript_editor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcript_editor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="transcript editor",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_transcript_reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcript_reviewer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="transcript reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_translation_editor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translation_editor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="translation editor",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_translation_reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translation_reviewer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="translation reviewer",
            ),
        ),
    ]
