# Generated by Django 3.2.16 on 2023-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_auto_20230106_0641"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_voiceover_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="Project Default VoiceOver Type",
            ),
        ),
    ]
