# Generated by Django 3.2.16 on 2023-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_alter_organization_default_task_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="enable_upload",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether CSV upload is enable or not.",
                verbose_name="enable_upload",
            ),
        ),
    ]
