# Generated by Django 3.2.16 on 2023-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_organization_enable_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="title",
            field=models.CharField(
                max_length=512, unique=True, verbose_name="organization_title"
            ),
        ),
    ]
