# Generated by Django 3.2.16 on 2023-06-09 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_alter_organization_default_transcript_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="default_target_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("en", "English"),
                        ("hi", "Hindi"),
                        ("as", "Assamese"),
                        ("bn", "Bengali"),
                        ("brx", "Bodo"),
                        ("doi", "Dogri"),
                        ("gu", "Gujarati"),
                        ("kn", "Kannada"),
                        ("ks", "Kashmiri"),
                        ("gom", "Konkani"),
                        ("mai", "Maithili"),
                        ("ml", "Malayalam"),
                        ("mr", "Marathi"),
                        ("mni", "Manipuri"),
                        ("ne", "Nepali"),
                        ("or", "Oriya"),
                        ("pa", "Punjabi"),
                        ("sa", "Sanskrit"),
                        ("sat", "Santali"),
                        ("sd", "Sindhi"),
                        ("ta", "Tamil"),
                        ("te", "Telugu"),
                        ("ur", "Urdu"),
                    ],
                    default=None,
                    max_length=50,
                    null=True,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Organization Default Target Languages",
            ),
        ),
    ]
