# Generated by Django 4.1.5 on 2023-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0012_alter_organization_default_target_languages")
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="default_translation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                    ("ORIGINAL_SOURCE", "Original Source"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="Default Translation Type",
            ),
        )
    ]
