# Generated by Django 4.1.5 on 2024-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0013_alter_organization_default_translation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardOrganisationAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orgname", models.CharField(max_length=265, verbose_name="orgname")),
                (
                    "org_portal",
                    models.CharField(max_length=512, verbose_name="org_portal"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email_address"
                    ),
                ),
                ("org_type", models.CharField(max_length=512, verbose_name="org_type")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ON_HOLD", "On Hold"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=35,
                        verbose_name="Onboarding Status",
                    ),
                ),
                (
                    "interested_in",
                    models.CharField(max_length=512, verbose_name="interested_in"),
                ),
                (
                    "src_language",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="src_language",
                    ),
                ),
                (
                    "tgt_language",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="tgt_language",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Purpose", max_length=1000, null=True
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        blank=True, help_text="Source", max_length=1000, null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for updating status",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
