# Generated by Django 4.1.5 on 2024-08-02 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0016_onboardorganisationaccount_email_domain_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="organization_owners",
            ),
        ),
    ]
