version: '3.8'

services:
  speech:
    build: ./speech-api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./speech-api/:/workspace/speech-api/
    ports:
      - 5000:5000