version: '3.8'

services:
  # speech:
  #   build: ./speech-api
  #   command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - driver: nvidia
  #   #           count: 1
  #   #           capabilities: [gpu]
  #   volumes:
  #     - ./speech-api/:/workspace/speech-api/
  #   ports:
  #     - 5000:5000
  
  translation:
    build: ./translation-api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5050"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    volumes:
      - ./translation-api/:/workspace/translation-api/
    ports:
      - 6060:5050