# Generated by Django 4.1.5 on 2024-02-04 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0013_alter_organization_default_translation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("as", "Assamese"),
                            ("bn", "Bengali"),
                            ("brx", "Bodo"),
                            ("doi", "Dogri"),
                            ("gu", "Gujarati"),
                            ("kn", "Kannada"),
                            ("ks", "Kashmiri"),
                            ("gom", "Konkani"),
                            ("mai", "Maithili"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("mni", "Manipuri"),
                            ("ne", "Nepali"),
                            ("or", "Oriya"),
                            ("pa", "Punjabi"),
                            ("sa", "Sanskrit"),
                            ("sat", "Santali"),
                            ("sd", "Sindhi"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=4,
                        verbose_name="Source Language",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("as", "Assamese"),
                            ("bn", "Bengali"),
                            ("brx", "Bodo"),
                            ("doi", "Dogri"),
                            ("gu", "Gujarati"),
                            ("kn", "Kannada"),
                            ("ks", "Kashmiri"),
                            ("gom", "Konkani"),
                            ("mai", "Maithili"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("mni", "Manipuri"),
                            ("ne", "Nepali"),
                            ("or", "Oriya"),
                            ("pa", "Punjabi"),
                            ("sa", "Sanskrit"),
                            ("sat", "Santali"),
                            ("sd", "Sindhi"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=4,
                        verbose_name="Target Language",
                    ),
                ),
                (
                    "source_text",
                    models.CharField(max_length=512, verbose_name="Source Text"),
                ),
                (
                    "target_text",
                    models.CharField(max_length=512, verbose_name="Target Text"),
                ),
                (
                    "org_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                        verbose_name="Glossary at org level",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
        ),
    ]
