# Generated by Django 4.1.5 on 2025-03-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0020_alter_task_target_language"),
        ("glossary", "0002_glossary_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossary",
            name="task_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="task.task"
            ),
        ),
        migrations.AddField(
            model_name="glossary",
            name="text_meaning",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Text Meaning"
            ),
        ),
        migrations.AlterField(
            model_name="glossary",
            name="source_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("as", "Assamese"),
                    ("bn", "Bengali"),
                    ("brx", "Bodo"),
                    ("doi", "Dogri"),
                    ("gu", "Gujarati"),
                    ("kn", "Kannada"),
                    ("ks", "Kashmiri"),
                    ("gom", "Konkani"),
                    ("mai", "Maithili"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Manipuri"),
                    ("ne", "Nepali"),
                    ("or", "Odia"),
                    ("pa", "Punjabi"),
                    ("sa", "Sanskrit"),
                    ("sat", "Santali"),
                    ("sd", "Sindhi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                max_length=4,
                verbose_name="Source Language",
            ),
        ),
        migrations.AlterField(
            model_name="glossary",
            name="target_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("as", "Assamese"),
                    ("bn", "Bengali"),
                    ("brx", "Bodo"),
                    ("doi", "Dogri"),
                    ("gu", "Gujarati"),
                    ("kn", "Kannada"),
                    ("ks", "Kashmiri"),
                    ("gom", "Konkani"),
                    ("mai", "Maithili"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Manipuri"),
                    ("ne", "Nepali"),
                    ("or", "Odia"),
                    ("pa", "Punjabi"),
                    ("sa", "Sanskrit"),
                    ("sat", "Santali"),
                    ("sd", "Sindhi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                max_length=4,
                verbose_name="Target Language",
            ),
        ),
    ]
