# Generated by Django 4.1.5 on 2025-03-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0020_alter_task_target_language"),
        ("glossary", "0003_glossary_task_id_glossary_text_meaning_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glossary",
            name="task_id",
        ),
        migrations.AddField(
            model_name="glossary",
            name="task_ids",
            field=models.ManyToManyField(to="task.task"),
        ),
    ]
