# Generated by Django 3.2.14 on 2022-12-08 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(help_text='Project Manager', related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
