# Generated by Django 3.2.16 on 2022-12-08 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_auto_20221208_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="managers",
            field=models.ManyToManyField(
                help_text="Project Managers",
                related_name="projects_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
