# Generated by Django 3.2.16 on 2023-01-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0005_auto_20230103_0526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="default_transcript_editor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_default_transcript_editor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Default Transcript Editor",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_transcript_reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_default_transcript_reviewer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Default Transcript Reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_translation_editor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_default_translation_editor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Default Translation Editor",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_translation_reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_default_translation_reviewer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Default Translation Reviewer",
            ),
        ),
    ]
