# Generated by Django 3.2.16 on 2022-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_auto_20221226_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="default_transcript_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORIGINAL_SOURCE", "Original Source"),
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="Project Default Transcript Type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_translation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                default=None,
                max_length=35,
                null=True,
                verbose_name="Project Default Translation Type",
            ),
        ),
    ]
