# Generated by Django 3.2.16 on 2023-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_project_video_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(help_text="Project Title", max_length=150),
        ),
    ]
