# Generated by Django 4.1.5 on 2024-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_pre_generate_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paraphrasing_enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether paraphrasing stage is enabled for the project', verbose_name='Paraphrasing Enabled'),
        ),
    ]
