# Generated by Django 4.1.7 on 2023-04-25 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0008_alter_project_default_task_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "youtube_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Youtube UUID",
                    ),
                ),
                (
                    "channel_id",
                    models.URLField(db_index=True, verbose_name="Youtube channel"),
                ),
                ("auth_token", models.JSONField(verbose_name="Auth token")),
                (
                    "project_id",
                    models.ForeignKey(
                        help_text="Organization to which the Project belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
