# Generated by Django 4.1.7 on 2023-05-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_project_default_task_types"),
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube",
            name="project_id",
            field=models.ForeignKey(
                help_text="Youtube to which the Project belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
        ),
    ]
