# Generated by Django 4.1.5 on 2023-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0002_alter_youtube_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube",
            name="channel_id",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Youtube channel"
            ),
        ),
    ]
