# Generated by Django 4.0.5 on 2022-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Video Name")),
                ("url", models.URLField(unique=True, verbose_name="Video URL")),
                ("duration", models.DurationField(verbose_name="Video Duration")),
            ],
        ),
    ]
