# Generated by Django 4.0.5 on 2022-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(db_index=True, unique=True, verbose_name='Video URL'),
        ),
    ]
