# Generated by Django 4.0.5 on 2022-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="subtitles",
            field=models.JSONField(blank=True, null=True, verbose_name="Subtitles"),
        ),
    ]
