# Generated by Django 4.0.5 on 2022-09-20 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_video_subtitles"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, null=True, verbose_name="Video UUID"
            ),
        ),
    ]
