# Generated by Django 4.0.5 on 2022-09-20 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Video UUID"),
        ),
    ]
