# Generated by Django 4.0.5 on 2022-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0006_remove_uuid_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_only",
            field=models.BooleanField(
                default=False,
                help_text="Does this object only contain audio?",
                verbose_name="Audio Only",
            ),
        ),
    ]
