# Generated by Django 3.2.16 on 2022-12-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_managers"),
        ("video", "0010_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="project_id",
            field=models.ForeignKey(
                help_text="Organization to which the Project belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
        ),
    ]
