# Generated by Django 3.2.16 on 2023-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0011_alter_video_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(db_index=True, verbose_name="Video URL"),
        ),
    ]
