# Generated by Django 4.1.7 on 2023-03-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0012_alter_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
