# Generated by Django 4.1.7 on 2023-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0012_alter_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="Male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
