# Generated by Django 3.2.16 on 2023-06-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0015_alter_video_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="speaker_info",
            field=models.JSONField(null=True, verbose_name="Speakers Info"),
        ),
    ]
