# Generated by Django 3.2.16 on 2023-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0016_video_speaker_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="multiple_speaker",
            field=models.BooleanField(
                default=False,
                help_text="Does this object have multiple speakers?",
                verbose_name="Multiple Speaker",
            ),
        ),
    ]
