# Generated by Django 3.2.16 on 2023-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0017_video_multiple_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="speaker_info",
            field=models.JSONField(blank=True, null=True, verbose_name="Speakers Info"),
        ),
    ]
