# Generated by Django 4.1.5 on 2024-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_alter_video_speaker_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('or', 'Oriya'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('sa', 'Sanskrit'), ('ur', 'Urdu')], max_length=4, verbose_name='Target Language'),
        ),
    ]
