# Generated by Django 4.1.5 on 2025-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0019_alter_video_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="yt_url",
            field=models.URLField(blank=True, null=True, verbose_name="Youtube URL"),
        ),
        migrations.AlterField(
            model_name="video",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("bn", "Bengali"),
                    ("gu", "Gujarati"),
                    ("kn", "Kannada"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("or", "Odia"),
                    ("pa", "Punjabi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("sa", "Sanskrit"),
                    ("ur", "Urdu"),
                    ("ne", "Nepali"),
                ],
                max_length=4,
                verbose_name="Target Language",
            ),
        ),
    ]
