# Generated by Django 4.0.5 on 2022-09-20 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0004_alter_translation_translation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="translation_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, null=True, verbose_name="Translation UUID"
            ),
        ),
    ]
