# Generated by Django 3.2.16 on 2022-11-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_language'),
        ('task', '0001_initial'),
        ('translation', '0007_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('TRANSLATION_SELECT_SOURCE', 'Translation selected source'), ('TRANSLATION_EDITOR_ASSIGNED', 'Translation Editor Assigned'), ('TRANSLATION_EDIT_INPROGRESS', 'Translation Edit Inprogress'), ('TRANSLATION_EDIT_COMPLETE', 'Translation Edit Complete'), ('TRANSLATION_REVIEWER_ASSIGNED', 'Translation Reviewer assigned'), ('TRANSLATION_REVIEW_INPROGRESS', 'Translation Review In-progress'), ('TRANSLATION_REVIEW_COMPLETE', 'Translation Review Complete')], default=None, max_length=35, verbose_name='Translation Status'),
        ),
        migrations.AddField(
            model_name='translation',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='translation_tasks', to='task.task', verbose_name='Task id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='translation_video', to='video.video', verbose_name='Translation Video ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(choices=[('MACHINE_GENERATED', 'Machine Generated'), ('UPDATED_MACHINE_GENERATED', 'Updated Machine Generated'), ('MANUALLY_CREATED', 'Manually Created')], max_length=35, verbose_name='Translation Type'),
        ),
    ]
