# Generated by Django 4.0.5 on 2023-11-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('as', 'Assamese'), ('bn', 'Bengali'), ('brx', 'Bodo'), ('doi', 'Dogri'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ks', 'Kashmiri'), ('gom', 'Konkani'), ('mai', 'Maithili'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('mni', 'Manipuri'), ('ne', 'Nepali'), ('or', 'Oriya'), ('pa', 'Punjabi'), ('sa', 'Sanskrit'), ('sat', 'Santali'), ('sd', 'Sindhi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu')], max_length=4, verbose_name='Target Language'),
        ),
    ]
