# Generated by Django 3.2.16 on 2022-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0008_auto_20221124_0615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translation_type",
            field=models.CharField(
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("ORIGINAL_SOURCE", "Original Source"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                max_length=35,
                verbose_name="Translation Type",
            ),
        ),
    ]
