# Generated by Django 4.1.5 on 2023-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0012_auto_20221228_0519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translation_type",
            field=models.CharField(
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                    ("MANUALLY_UPLOADED", "Manually Uploaded"),
                ],
                max_length=35,
                verbose_name="Translation Type",
            ),
        ),
    ]
