# Generated by Django 3.2.16 on 2023-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0014_alter_translation_translation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("as", "Assamese"),
                    ("bn", "Bengali"),
                    ("brx", "Bodo"),
                    ("doi", "Dogri"),
                    ("gu", "Gujarati"),
                    ("kn", "Kannada"),
                    ("ks", "Kashmiri"),
                    ("gom", "Konkani"),
                    ("mai", "Maithili"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Manipuri"),
                    ("ne", "Nepali"),
                    ("or", "Oriya"),
                    ("pa", "Punjabi"),
                    ("sa", "Sanskrit"),
                    ("sat", "Santali"),
                    ("sd", "Sindhi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                max_length=4,
                verbose_name="Target Language",
            ),
        ),
    ]
