# Generated by Django 4.1.5 on 2023-12-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0016_alter_translation_translation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translation_type",
            field=models.CharField(
                choices=[
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                ],
                max_length=35,
                verbose_name="Translation Type",
            ),
        ),
    ]
