# Generated by Django 4.0.5 on 2022-07-02 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video", "0002_alter_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="transcript_id",
                    ),
                ),
                (
                    "transcript_type",
                    models.CharField(
                        choices=[
                            ("machine_generated", "machine_generated"),
                            ("human_edited", "human_edited"),
                            ("human_edited", "manually_created"),
                        ],
                        default="machine_generated",
                        max_length=50,
                        verbose_name="transcript_type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Hindi", "Hindi")],
                        default="English",
                        max_length=50,
                        verbose_name="transcription_language",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="transcription_output")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="transcription_created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="transcription_updated_at"
                    ),
                ),
                (
                    "parent_transcript",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transcript.transcript",
                        verbose_name="parent_transcript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="transcriptor",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="video.video",
                        verbose_name="transcript_video_id",
                    ),
                ),
            ],
        ),
    ]
