# Generated by Django 4.0.5 on 2022-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcript", "0006_alter_transcript_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="transcript_type",
            field=models.CharField(
                choices=[
                    ("os", "Original Source"),
                    ("uos", "Updated Original Source"),
                    ("mg", "Machine Generated"),
                    ("umg", "Updated Machine Generated"),
                    ("mc", "Manually Created"),
                ],
                default="mg",
                max_length=10,
                verbose_name="Transcript Type",
            ),
        ),
    ]
