# Generated by Django 4.0.5 on 2023-11-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0008_alter_transcript_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('as', 'Assamese'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('or', 'Oriya'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=10, verbose_name='Transcript Language'),
        ),
    ]
