# Generated by Django 3.2.16 on 2022-12-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcript", "0009_auto_20221124_0615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="parent_transcript",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcript.transcript",
                verbose_name="Parent Transcript",
            ),
        ),
    ]
