# Generated by Django 3.2.16 on 2022-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcript", "0010_alter_transcript_parent_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="payload",
            field=models.JSONField(null=True, verbose_name="Transcription Output"),
        ),
    ]
