# Generated by Django 4.1.5 on 2023-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcript", "0011_alter_transcript_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="transcript_type",
            field=models.CharField(
                choices=[
                    ("ORIGINAL_SOURCE", "Original Source"),
                    ("MACHINE_GENERATED", "Machine Generated"),
                    ("MANUALLY_CREATED", "Manually Created"),
                    ("MANUALLY_UPLOADED", "Manually Uploaded"),
                ],
                default="MACHINE_GENERATED",
                max_length=35,
                verbose_name="Transcript Type",
            ),
        ),
    ]
