# Generated by Django 4.1.5 on 2024-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0014_alter_transcript_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('or', 'Oriya'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('sa', 'Sanskrit'), ('ur', 'Urdu')], default='en', max_length=10, verbose_name='Transcript Language'),
        ),
    ]
