# Generated by Django 4.1.5 on 2023-10-19 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribed_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "newsletter_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Newsletter UUID",
                    ),
                ),
                ("content", models.TextField(help_text="Newsletter Content")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("NEW_FEATURE", "New Feature")],
                        default=None,
                        max_length=35,
                        null=True,
                        verbose_name="Category of newsletter",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Newsletter Created At"
                    ),
                ),
                (
                    "submitter_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_submitter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="newsletter_submitter",
                    ),
                ),
            ],
        ),
    ]
