# Generated by Django 4.1.5 on 2023-11-03 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribedusers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitter Name",
            ),
        ),
    ]
