# Generated by Django 4.1.5 on 2023-11-03 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsletter", "0002_alter_subscribedusers_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="submitter_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitter User",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscribedusers",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
