# Generated by Django 4.1.5 on 2023-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_alter_newsletter_submitter_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedusers",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email_address"
            ),
        ),
    ]
