# Generated by Django 4.1.5 on 2024-01-03 18:33

import django.contrib.postgres.fields
from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0005_alter_newsletter_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedusers",
            name="subscribed_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("RELEASE", "Release"),
                        ("DOWNTIME", "Downtime"),
                        ("GENERAL", "General"),
                    ],
                    max_length=20,
                ),
                default=list,
                size=None,
                validators=[newsletter.models.validate_category_choices],
            ),
        ),
    ]
