# Generated by Django 3.2.16 on 2022-11-24 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video", "0009_video_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Task UUID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("TRANSCRIPTION_EDIT", "Transcription Edit"),
                            ("TRANSCRIPTION_REVIEW", "Transcription Review"),
                            ("TRANSLATION_EDIT", "Translation Edit"),
                            ("TRANSLATION_REVIEW", "Translation Review"),
                            (
                                "TRANSCRIPTION_SELECT_SOURCE",
                                "Transcription Select Source",
                            ),
                            ("TRANSLATION_SELECT_SOURCE", "Translation Select Source"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("as", "Assamese"),
                            ("bn", "Bengali"),
                            ("brx", "Bodo"),
                            ("gu", "Gujarati"),
                            ("kn", "Kannada"),
                            ("ks", "Kashmiri"),
                            ("gom", "Konkani"),
                            ("mai", "Maithili"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("mni", "Manipuri"),
                            ("ne", "Nepali"),
                            ("or", "Oriya"),
                            ("pa", "Punjabi"),
                            ("sa", "Sanskrit"),
                            ("sd", "Sindhi"),
                            ("si", "Sinhala"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=4,
                        verbose_name="Target Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("INPROGRESS", "INPROGRESS"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        default=None,
                        max_length=35,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Task Created By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Task Assignee",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="video.video",
                        verbose_name="Task Video ID",
                    ),
                ),
            ],
        ),
    ]
