# Generated by Django 3.2.16 on 2022-11-29 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, help_text="Task Description", max_length=400, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="eta",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="ETA",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "Priority No 1"),
                    ("P2", "Priority No 2"),
                    ("P3", "Priority No 3"),
                    ("P4", "Priority No 4"),
                ],
                max_length=2,
                verbose_name="Priority",
            ),
        ),
    ]
