# Generated by Django 3.2.16 on 2022-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_auto_20221201_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="verified_transcript",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
