# Generated by Django 3.2.16 on 2022-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_auto_20221214_0732"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this task is accessible to the assignee.",
                verbose_name="active",
            ),
        ),
    ]
