# Generated by Django 3.2.16 on 2022-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_auto_20221214_0732"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this task is accessible to the assignee.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "Priority No 1"),
                    ("P2", "Priority No 2"),
                    ("P3", "Priority No 3"),
                    ("P4", "Priority No 4"),
                ],
                max_length=2,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
