# Generated by Django 3.2.16 on 2022-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_task_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "Priority No 1"),
                    ("P2", "Priority No 2"),
                    ("P3", "Priority No 3"),
                    ("P4", "Priority No 4"),
                ],
                max_length=2,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
