# Generated by Django 3.2.16 on 2023-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0008_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("SELECTED_SOURCE", "Selected Source"),
                    ("INPROGRESS", "In Progress"),
                    ("COMPLETE", "Complete"),
                ],
                default=None,
                max_length=35,
                verbose_name="Task Status",
            ),
        ),
    ]
