# Generated by Django 3.2.16 on 2023-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0009_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("TRANSCRIPTION_EDIT", "Transcription Edit"),
                    ("TRANSCRIPTION_REVIEW", "Transcription Review"),
                    ("TRANSLATION_EDIT", "Translation Edit"),
                    ("TRANSLATION_REVIEW", "Translation Review"),
                    ("VOICEOVER_EDIT", "VoiceOver Edit"),
                    ("VOICEOVER_REVIEW", "VoiceOver Review"),
                ],
                max_length=35,
            ),
        ),
    ]
