# Generated by Django 3.2.16 on 2023-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0013_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time_spent",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Time Spent"
            ),
        ),
    ]
