# Generated by Django 4.1.5 on 2025-03-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0019_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="target_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("as", "Assamese"),
                    ("bn", "Bengali"),
                    ("brx", "Bodo"),
                    ("doi", "Dogri"),
                    ("gu", "Gujarati"),
                    ("kn", "Kannada"),
                    ("ks", "Kashmiri"),
                    ("gom", "Konkani"),
                    ("mai", "Maithili"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Manipuri"),
                    ("ne", "Nepali"),
                    ("or", "Odia"),
                    ("pa", "Punjabi"),
                    ("sa", "Sanskrit"),
                    ("sat", "Santali"),
                    ("sd", "Sindhi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                max_length=4,
                verbose_name="Target Language",
            ),
        ),
    ]
