# Generated by Django 4.1.5 on 2025-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.JSONField(blank=True, default=dict, help_text='field to store task completion details', null=True),
        ),
    ]
