# Generated by Django 3.2.16 on 2022-10-12 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=265, verbose_name="username")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email_address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=265, verbose_name="first_name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=265, verbose_name="last_name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=256, verbose_name="phone"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Transcript editor"),
                            (2, "Transcript Reviewer"),
                            (3, "Translation editor"),
                            (4, "Translation Reviewer"),
                            (5, "Universal Editor"),
                            (6, "Project Manager"),
                            (7, "Organization Owner"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "has_accepted_invite",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has accepted the invite.",
                        verbose_name="invite status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether to treat this user as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "enable_mail",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether mailing is enable or not.",
                        verbose_name="enable_mail",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "activity_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="last annotation activity by the user",
                    ),
                ),
                (
                    "availability_status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Available"), (2, "On Leave")],
                        default=1,
                        help_text="Indicates whether a user is available for doing assigned tasks or not.",
                    ),
                ),
                ("unverified_email", models.EmailField(blank=True, max_length=254)),
                ("old_email_update_code", models.CharField(blank=True, max_length=256)),
                (
                    "new_email_verification_code",
                    models.CharField(blank=True, max_length=256),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="user_usernam_b79065_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_7bbb4c_idx"),
        ),
    ]
