# Generated by Django 3.2.16 on 2022-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20221014_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("TRANSCRIPT_EDITOR", "Transcript editor"),
                    ("TRANSCRIPT_REVIEWER", "Transcript Reviewer"),
                    ("TRANSLATION_EDITOR", "Translation editor"),
                    ("TRANSLATION_REVIEWER", "Translation Reviewer"),
                    ("UNIVERSAL_EDITOR", "Universal Editor"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("ORG_OWNER", "Organization Owner"),
                ],
                default="TRANSCRIPT_EDITOR",
            ),
        ),
    ]
