# Generated by Django 3.2.16 on 2022-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("TRANSCRIPT_EDITOR", "Transcript editor"),
                    ("TRANSCRIPT_REVIEWER", "Transcript Reviewer"),
                    ("TRANSLATION_EDITOR", "Translation editor"),
                    ("TRANSLATION_REVIEWER", "Translation Reviewer"),
                    ("UNIVERSAL_EDITOR", "Universal Editor"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("ORG_OWNER", "Organization Owner"),
                    ("ADMIN", "Admin"),
                ],
                max_length=25,
            ),
        ),
    ]
