# Generated by Django 4.1.5 on 2023-11-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date joined"
            ),
        ),
    ]
