# Generated by Django 4.1.5 on 2024-01-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tips",
            field=models.BooleanField(
                default=True,
                help_text="Checks if the user is first time or not to display user guide.",
                verbose_name="tips for flow",
            ),
        ),
    ]
