# Generated by Django 4.1.5 on 2024-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_tips"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_history",
            field=models.JSONField(null=True, verbose_name="User History"),
        ),
    ]
