# Generated by Django 3.2.16 on 2023-02-09 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("video", "0012_alter_video_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0010_alter_task_task_type"),
        ("translation", "0012_auto_20221228_0519"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceOver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voice_over_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Voice Over UUID",
                    ),
                ),
                (
                    "voice_over_type",
                    models.CharField(
                        choices=[("MANUALLY_CREATED", "Manually Created")],
                        max_length=35,
                        verbose_name="Voice Over Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VOICEOVER_SELECT_SOURCE", "Voice Over selected source"),
                            ("VOICEOVER_EDITOR_ASSIGNED", "Voice Over Editor Assigned"),
                            ("VOICEOVER_EDIT_INPROGRESS", "Voice Over Edit Inprogress"),
                            ("VOICEOVER_EDIT_COMPLETE", "Voice Over Edit Complete"),
                            (
                                "VOICEOVER_REVIEWER_ASSIGNED",
                                "Voice Over Reviewer assigned",
                            ),
                            (
                                "VOICEOVER_REVIEW_INPROGRESS",
                                "Voice Over Review In-progress",
                            ),
                            ("VOICEOVER_REVIEW_COMPLETE", "Voice Over Review Complete"),
                        ],
                        default=None,
                        max_length=35,
                        verbose_name="Voice Over Status",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(null=True, verbose_name="Voice Over Output"),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("as", "Assamese"),
                            ("bn", "Bengali"),
                            ("brx", "Bodo"),
                            ("gu", "Gujarati"),
                            ("kn", "Kannada"),
                            ("ks", "Kashmiri"),
                            ("gom", "Konkani"),
                            ("mai", "Maithili"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("mni", "Manipuri"),
                            ("ne", "Nepali"),
                            ("or", "Oriya"),
                            ("pa", "Punjabi"),
                            ("sa", "Sanskrit"),
                            ("sd", "Sindhi"),
                            ("si", "Sinhala"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=4,
                        verbose_name="Target Language",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Voice Over Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Voice Over Updated At"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voiceover.voiceover",
                        verbose_name="Parent Voice Over",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_over_tasks",
                        to="task.task",
                        verbose_name="Task id",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_overs",
                        to="translation.translation",
                        verbose_name="Voice Over Transcript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Speaker",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_over_video",
                        to="video.video",
                        verbose_name="Voice Over Video ID",
                    ),
                ),
            ],
        ),
    ]
