# Generated by Django 3.2.16 on 2023-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceover", "0002_alter_voiceover_voice_over_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceover",
            name="azure_url",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="azure_url"
            ),
        ),
    ]
