# Generated by Django 3.2.16 on 2023-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voiceover", "0004_alter_voiceover_target_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceover",
            name="azure_url_audio",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="azure_url_audio"
            ),
        ),
    ]
